# /boot/loader.conf bsdlab

# loader
boot_mute="YES"
beastie_disable="YES"
autoboot_delay="2"
efi_max_resolution="1920x1080x32"

# microcode
cpu_microcode_load="YES"
cpu_microcode_name="/boot/firmware/amd-ucode.bin"

# kern
kernels="kernel"
kern.coredump=0

# Modules
vmm_load="YES" # virtual machine manager
if_tap_load="YES"
if_bridge_load="YES"
nmdm_load="YES"

# DRM
linux_common_load="YES"
linprocfs_load="YES"
lindebugfs_load="YES"
drm_load="YES"
drmn_load="YES"
amdgpu_load="YES"

#ahci_load="YES"
#coretemp_load="YES"
#machdep.hyperthreading_allowed="1"

# snd
snd_driver_load="YES"

# rtprio(1) for users
mac_priority_load="YES" 

# crypto
kern.random.fortuna.minpoolsize="2048"
aesni_load="YES"
cryptodev_load="YES"
geom_eli_load="YES"

# sec
#hardening.harden_rtld=0
#hardening.elf_pie_only=1
#secadm_load="YES"
security.bsd.allow_destructive_dtrace=0
security.bsd.see_jail_proc=0
security.bsd.see_other_uids=1
security.bsd.see_other_gids=1
#security.bsd.unprivileged_mlock=0
security.bsd.unprivileged_read_msgbuf=0
security.bsd.unprivileged_proc_debug=0
security.bsd.hardlink_check_gid=0
security.bsd.hardlink_check_uid=0
#security.bsd.stack_guard_page=1
kern.ipc.shm_use_phys=1


# Disk / ZFS
zfs_load="YES"
vfs.root.mountfrom="zfs:zsys/ROOT/bsdlab"
hw.usb.no_boot_wait="1"
hw.usb.no_shutdown_wait=1
kern.geom.label.disk_ident.enable="0"
kern.geom.label.gptid.enable="0"
vfs.zfs.arc.max=8589934592 # 8GB
vfs.zfs.arc.min=4294967296 # 4GB

# 
fusefs_load="YES"

#
hw.syscons.bell=0

# qemu tap
#net.link.tap.user_open=1

# prevent traffic analysis that exploits sequential IP IDs
net.inet.ip.random_id=1

#vm.swap_idle_enabled=1
#kern.consmute=1

# Network
#net.inet.ip.forwarding=1
#net.inet.tcp.mssdflt=1460
#net.inet.tcp.minmss=536
#net.inet.tcp.syncache.rexmtlimit=0
#net.inet.ip.maxfragpackets=0     # (default 13687)
#net.inet.ip.maxfragsperpacket=0  # (default 16)
#net.inet.tcp.abc_l_var=44  # (default 2)
#net.inet.tcp.initcwnd_segments=44             # (default 10 for FreeBSD 11.0)
#net.inet.tcp.experimental.initcwnd10=1       # (default  1 for FreeBSD 10.1)
#net.inet.tcp.experimental.initcwnd10=1       # (default  0 for FreeBSD  9.2)
#net.inet.tcp.local_slowstart_flightsize=44   # (default  4 for FreeBSD  9.1)
#net.inet.tcp.slowstart_flightsize=44         # (default  4 for FreeBSD  9.1)
#kern.ipc.maxsockbuf=614400000  # (wsize 14)
#net.inet.tcp.isn_reseed_interval=4500  # (default 0, disabled)
#net.inet.icmp.drop_redirect=1      # no redirected ICMP packets (default 0)
#net.inet.ip.portrange.first=1024   # use ports 1024 to portrange.last for outgoing connections (default 10000)
#net.inet.ip.random_id=1            # assign a random IP id to each packet leaving the system (default 0)
#net.inet.ip.redirect=0             # do not send IP redirects (default 1)
#net.inet.tcp.always_keepalive=0    # disable tcp keep alive detection for dead peers, keepalive can be spoofed (default 1)
#net.inet.tcp.blackhole=2           # drop tcp packets destined for closed ports (default 0)
#net.inet.tcp.drop_synfin=1         # SYN/FIN packets get dropped on initial connection (default 0)
#net.inet.tcp.ecn.enable=1          # Explicit Congestion Notification disabled unless proper active queue management is verified (default 2)
#net.inet.tcp.icmp_may_rst=0        # icmp may not send RST to avoid spoofed icmp/udp floods (default 1)
#net.inet.tcp.keepinit=5000         # establish connection in five(5) seconds or abort attempt (default 75000, 75 secs)
#net.inet.tcp.msl=2500              # Maximum Segment Lifetime, time the connection spends in TIME_WAIT state (default 30000, 2*MSL = 60 sec)
#net.inet.tcp.rexmit_slop=70        # reduce the TCP retransmit timer, min+slop=100ms (default 200ms)
#net.inet.udp.blackhole=1           # drop udp packets destined for closed sockets (default 0)





# vmm
hw.vmm.amdvi.enable="1"
#pptdevs="6/0/0 6/0/1 1/0/0 8/0/3"
