#!/bin/sh
# /etc/rc.conf bsdlab

#
# System
#

# kern
kld_list="pf pflog secadm amdgpu" # geom_nbd

# Hostname
hostname="bsdlab"

# Console
rc_info="YES"
keymap="de.kbd"
keyrate="fast"
moused_nondefault_enable="NO"

# no dumps
dumpdev="NO"

# ZFS
zfs_enable="YES"

# zUser ZFS Pool per GELI + geli swap
geli_devices="gpt/zuser0 gpt/zuser1"
geli_swap_flags="-e AES-XTS -l 256"
geli_gpt_zuser0_flags="-p -k /etc/keys/ada1.key"
geli_gpt_zuser1_flags="-p -k /etc/keys/ada2.key"


#
# Security
#

# secadm
secadm_enable="YES"

# Secure-Level
#kern_securelevel_enable="YES"
#kern_securelevel="-1"

# Audit Daemon
#auditd_enable="YES"

# System Logger
syslogd_enable="YES"
syslogd_flags="-ss"


#
# Services
#

# NTP
chronyd_enable="YES"

# Desktop Services
dbus_enable="YES"
seatd_enable="YES"

# virt-manager
libvirtd_enable="YES"

# Disk Monitor
smartd_enable="YES"


#
# Network
#

# Default Firewall
#firewall_enable="YES"
#firewall_type="workstation"

#firewall_myservices="22/tcp"
#firewall_allowservices="any"
#firewall_logging="YES" 
#firewall_logdeny="YES"
##firewall_coscripts="/usr/local/etc/openvpn/firewall.sh" # prevent dnsleaks

# dhcpcd
#dhcpcd_enable="YES"
#dhclient_program="/usr/local/sbin/dhcpcd"
#dhclient_flags="-S domain_name_servers=1.1.1.1"


# Ethernet
ifconfig_re0="DHCP"
background_dhclient_re0="YES"

# USB Tethering
ifconfig_ue0="DHCP"
background_dhclient_ue0="YES"


vm_enable="YES"
vm_dir="zfs:zsys/vmm"
vm_list="lnxlab"

# nfsv3 für ps4
rpcbind_enable="YES"
nfs_server_enable="YES"
mountd_enable="YES"
rpc_lockd_enable="YES"
rpc_statd_enable="YES"
nfs_server_flags="-u -t -n 6"
mountd_flags="-r"
weak_mountd_authentication="YES"
