splash = false
ipc = off

wallpaper {
    monitor = DP-1
    path = ~/Bilder/background.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Bilder/background.jpg
    fit_mode = cover
}
