-- ~/.config/hypr/hyprland.conf kirby@bsdlab
-- THIS FILE WAS AUTO-GENERATED BY https://eiontusk.github.io/hyprlang2lua/

--
-- Variables
--

-- Monitors
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "0",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "1",
    mode = "1920x1200@60",
    position = "1920x0",
    scale = "1",
})

-- Environment Variables
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XDG_RUNTIME_DIR", "/var/run/xdg/kirby")

-- Set programs that you use
local terminal = "footclient"
local menu = "wofi --show run"
local screenshot = "grimshot copy area"
local editor = "emacs"

--
-- Window & Workspace Rules
--

-- Workspaces
hl.workspace_rule({
    workspace = "1",
    monitor = 0,
    persistent = true,
    default = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = 0,
    persistent = true,
})

hl.workspace_rule({
    workspace = "3",
    monitor = 0,
    persistent = true,
})

hl.workspace_rule({
    workspace = "4",
    monitor = 0,
    persistent = true,
})

hl.workspace_rule({
    workspace = "5",
    monitor = 0,
    persistent = true,
})

hl.workspace_rule({
    workspace = "6",
    monitor = 1,
    persistent = true,
    default = true,
})

hl.workspace_rule({
    workspace = "7",
    monitor = 1,
    persistent = true,
})

hl.workspace_rule({
    workspace = "8",
    monitor = 1,
    persistent = true,
})

hl.workspace_rule({
    workspace = "9",
    monitor = 1,
    persistent = true,
})

hl.workspace_rule({
    workspace = "10",
    monitor = 1,
    persistent = true,
})

--
-- Autostart in Workspace
--
--exec-once = [workspace 3 silent] signal-desktop
--exec-once = [workspace 5 silent] 
--exec-once = [workspace 6 silent]
--exec-once = [workspace 3 silent]
--exec-once = [workspace 3 silent]
--exec-once = [workspace 3 silent]
--exec-once = [workspace 3 silent] 

--
-- Autostart 
--

-- cliphist

--
-- Key-Bindings
--

-- See https://wiki.hyprland.org/Configuring/Keywords/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier

-- https://wiki.hyprland.org/Configuring/Binds/

-- Programs
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("$fileManager"))
--mod+shift+c:SIGUSR1 an DE
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.exec_raw(screenshot))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(editor))

-- cliphist
hl.bind("SUPER + V", hl.dsp.exec_cmd("cliphist list | wofi --show dmenu | cliphist decode | wl-copy"))

-- WM Control
hl.bind(mainMod .. " + ALT + q", hl.dsp.exit())
hl.bind(mainMod .. " + W", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.window.kill())
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
--Window States... (sticky,floating,pinned,etc)

-- Navigation
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))

hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "u" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

-- Audio
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ +2%"))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("pactl set-sink-volume @DEFAULT_SINK@ -2%"))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("pactl set-sink-mute @DEFAULT_SINK@ toggle"))
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"))

--XF86AudioPrev
--XF86AudioNext
--XF86AudioPlay
-- lookup xkbcommon-keysyms.h header
--bind = SUPER, code:28, exec, amongus

--
-- Configuring
--

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "myBezier",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 7,
    bezier = "default",
    style = "popin 80%",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 8,
    bezier = "default",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default",
})

hl.config({
    general = {
        gaps_in = 3,
        gaps_out = 15,
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        col = {
            active_border = "rgb(817f7f)",
            inactive_border = "rgb(30302f)",
        },
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = false,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#decoration
    decoration = {
        rounding = 7,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        --drop_shadow = false
        --shadow_range = 1
        --shadow_render_power = 3
        --col.shadow = rgba(1a1a1aee)
        -- https://wiki.hyprland.org/Configuring/Variables/#blur
        blur = {
            enabled = true,
            size = 10,
            passes = 1,
            brightness = 0.7,
        },
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#animations
    animations = {
        enabled = false,
        -- Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    },
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    dwindle = {
        --pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
        preserve_split = true, -- You probably want this
    },
    -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#misc
    misc = {
        --vfr = true
        force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
        font_family = "Fira Code",
    },
    -- https://wiki.hyprland.org/Configuring/Variables/#input
    input = {
        kb_layout = "de",
        kb_options = "ctrl:nocaps",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = false,
        },
    },
    render = {
        direct_scanout = false,
    },
    xwayland = {
        force_zero_scaling = true,
    },
})

hl.on("hyprland.start", function()
    hl.exec_cmd("emacs ~/Workspace/Todo.md", { workspace = "1" })
    hl.exec_cmd("firefox", { workspace = "2 silent" })
    hl.exec_cmd("thunderbird", { workspace = "4 silent" })
    hl.exec_cmd("dbus-launch waybar &")
    hl.exec_cmd("hyprpaper &")
    hl.exec_cmd("dbus-launch emacs --fg-daemon &")
    hl.exec_cmd("dbus-launch dunst &")
    hl.exec_cmd("dbus-launch pulseaudio --start &")
    hl.exec_cmd("dbus-launch foot --server &")
    hl.exec_cmd("ssh-agent -a $XDG_RUNTIME_DIR/ssh-agent.sock")
    hl.exec_cmd("wl-paste --type text --watch cliphist store &")
    hl.exec_cmd("wl-paste --type image --watch cliphist store &")
end)
